### ISSUE TITLE
GET_FACE_ARTIFACTS_ACCESS returns 500 Internal Server Error

### ISSUE THREAD

**Issue by mktelos** [Azure-Samples/azure-ai-vision-sdk#103]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
I have an issue that started happening since yesterday when I am trying to generate a new Access Token or querying the Access Token, the request returns a 500 Internal Server Error. This was working fine before I was able to generate and query the token but since yesterday I am getting a 500 response. The resource is configured properly (I can use Face API Rest API) , I have the necessary role and the subscription was approved for this API since I was able to use it before.

These are the endpoints I am invoking from [GET_FACE_ARTIFACTS_ACCESS.md](https://github.com/Azure-Samples/azure-ai-vision-sdk/blob/main/GET_FACE_ARTIFACTS_ACCESS.md)

POST https://face-sdk-gating-helper-2.azurewebsites.net/sdk/subscriptions/{subscriptionId}/tokens?id={tokenId}

GET https://face-sdk-gating-helper-2.azurewebsites.net/sdk/subscriptions/{subscriptionId}/tokens?id={tokenId}

**Comment by diljale** [comment]
I believe this issue is now resolved. Please try it again. Thanks
