### ISSUE TITLE
Get photo after liveness verify

### ISSUE THREAD

**Issue by Bestfastfire** [Azure-Samples/azure-ai-vision-sdk#104]
I'm implementing the liveness system but I need to get the photo taken at the time of verification, but I didn't find a way to do this, I even tried to get a "print" of the preview on Android but it is displayed on a surfaceview, every attempt I make I did always return a blank image.

Is there any way to get this image still on android while checking this?

**Comment by nabilat** [comment]
Hello, we have this feature in our **v1.2-preview.1** APIs, you will need to update all your endpoints to specify **v1.2-preview.1** for this to work:
For example: https://(endpoint)/face/**v1.2-preview.1**/detectliveness/singlemodal

Here’s the steps:

1. Set the “enableSessionImage” boolean to true when creating the session:

![image](https://github.com/Azure-Samples/azure-ai-vision-sdk/assets/15527981/6c99454a-7d63-4564-b0e8-b3a474ee1a62)

2. Get the “sessionImageId” from the session result:

![image](https://github.com/Azure-Samples/azure-ai-vision-sdk/assets/15527981/9e39c820-5d18-43cf-8a8b-1fa53247d89c)

3. Call the session/sessionImages/{sessionImageId} endpoint to get the image:

![image](https://github.com/Azure-Samples/azure-ai-vision-sdk/assets/15527981/bb7be124-66c6-4404-80a5-0e28326ae95f)

**Comment by Bestfastfire** [comment]
> Hello, we have this feature in our **v1.2-preview.1** APIs, you will need to update all your endpoints to specify **v1.2-preview.1** for this to work: For example: https://(endpoint)/face/**v1.2-preview.1**/detectliveness/singlemodal
> 
> Here’s the steps:
> 
> 1. Set the “enableSessionImage” boolean to true when creating the session:
> 
> ![image](https://private-user-images.githubusercontent.com/15527981/345161157-6c99454a-7d63-4564-b0e8-b3a474ee1a62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMjg2MjgsIm5iZiI6MTcyMTEyODMyOCwicGF0aCI6Ii8xNTUyNzk4MS8zNDUxNjExNTctNmM5OTQ1NGEtN2Q2My00NTY0LWIwZTgtYjNhNDc0ZWUxYTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDExMTIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0ZjJhNjZkYjgxNWQ1YWJlZWNmYzEwMzc5MmM2OWY4Mjc3NGNlZDk3MTUwMzI4YTExMzI5NzFkYjA1ZGY3MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8-pmFGagQPRulmEAsX0t6sryWMaJG80g6nlQ5sSJasw)
> 
> 2. Get the “sessionImageId” from the session result:
> 
> ![image](https://private-user-images.githubusercontent.com/15527981/345161604-9e39c820-5d18-43cf-8a8b-1fa53247d89c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMjg2MjgsIm5iZiI6MTcyMTEyODMyOCwicGF0aCI6Ii8xNTUyNzk4MS8zNDUxNjE2MDQtOWUzOWM4MjAtNWQxOC00M2NmLThhOGItMWZhNTMyNDdkODljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDExMTIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2NTQxYjMyMDE1ZjUzMDQ0Mjk5Y2UxNjQ1YzZjNjM5Zjc5NjkyMWIxMjc4ZmUzNTIzN2E2NDc0MjZiMGIxOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P1GE4usM53_SJ8MUtnoRWvqMvrePNd99CtccWdYaJs0)
> 
> 3. Call the session/sessionImages/{sessionImageId} endpoint to get the image:
> 
> ![image](https://private-user-images.githubusercontent.com/15527981/345162110-bb7be124-66c6-4404-80a5-0e28326ae95f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMjg2MjgsIm5iZiI6MTcyMTEyODMyOCwicGF0aCI6Ii8xNTUyNzk4MS8zNDUxNjIxMTAtYmI3YmUxMjQtNjZjNi00NDA0LTgwYTUtMGUyODMyNmFlOTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDExMTIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiZWYwZTAzM2YwY2NmYWE2YTQwNjBhYzliMjZmM2JkZjhiNWU3NzI0MThmMTA3YWFkNjNhM2FiMDFkNmY4YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ms826RcGj6nJrDSNx-9B_hnXc_T7YFJVLeWLf0ZbpoM)

What is the ID I give in step 2 in: /sessions/ID

I tried the sessionId using the bearer token that comes with the session creation, but I get this error:

```
{
    "error": {
        "code": "PermissionDenied",
        "message": "Access denied due to request URL not permitted by scopes specified within the token."
    }
}
```

**Comment by dsschiramm** [comment]
@nabilat 

I'm receiving "Access denied due to request URL not permitted by scopes specified within the token" when I request this "session/sessionImages/{sessionImageId}" URL.

Can you tell me the permissions?
I will use this in production, is it ok?

**Comment by sca1235** [comment]
Works for us the only issue is the quality is all messed up. Not sure if encoding is weird but we did as a jpg. Is it base64 image or what is best format we should be doing to display this.

The image is pixelated oddly.

**Comment by dsschiramm** [comment]
@sca1235 you know something about "Access denied due to request URL not permitted by scopes specified within the token"?

**Comment by Bestfastfire** [comment]
> @sca1235 hello! can i see the code you used to format and see the image from the session/sessionImages/{sessionImageId} call

You can download it like this:

const axios = require('axios');
const fs = require('fs');
const path = require('path');

const url = 'https://YOUR_ENDPOINT/face/v1.2-preview.1/session/sessionImages/IMAGE_SESSION_ID';
const apiKey = 'YOUR_KEY';
const outputFilePath = path.resolve(__dirname, 'downloaded_image.png');

axios({
    method: 'get',
    url: url,
    responseType: 'arraybuffer',
    headers: {
        'Ocp-Apim-Subscription-Key': apiKey
    }
})
.then(response => {
    fs.writeFileSync(outputFilePath, response.data);
    console.log('Image downloaded successfully!');
})
.catch(error => {
    console.error('Error downloading the image', error);
});

**Comment by sca1235** [comment]
@cheymonty So I did some more debugging the problem appears only with certain device. Iphone, mac etc work fine.

Using an Microsoft Surface Laptop Studio 2 has this issue. Not sure if this is hardware or some software setting thats disrupting. 

This is example of the pixelation

![image](https://github.com/user-attachments/assets/14027134-1127-4fb3-9026-a2e0fb9df211)
