### ISSUE TITLE
Liveness Detection JS SDK

### ISSUE THREAD

**Issue by albertovillalon** [Azure-Samples/azure-ai-vision-sdk#111]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
I am interested in the Microsoft JS SDK for liveness detection, which I understand is currently in a private beta phase. This SDK is crucial for a project I'm working on, and I am keen to learn more about its functionalities and potential integration.

Could you please provide information on when access to this SDK will be generally available or how I might apply to participate in the private beta? Any updates or details you can share would be greatly appreciated.

Thank you for your time and assistance.

**Comment by diljale** [comment]
The JS SDK is now in public preview. Here is sample on using the same https://github.com/Azure-Samples/azure-ai-vision-sdk/tree/main/samples/nextjs

Let me know if you run into any issues.
