### ISSUE TITLE
Documentation for Liveness Dectection is Missing for .NET SDK  that needs to be used in the Mobile (.NET MAUI)

### ISSUE THREAD

**Issue by marounelkadyNetiks** [Azure-Samples/azure-ai-vision-sdk#114]
This issue is for a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

I am going through the documentation and I am planning to use the Liveness Detection Feature of Azure AI Vision in MAUI. 
The Back end Server Side functions were documented (Creating and Deleting Session and Getting the result). However the Front End (Mobile Side) is not documented for .NET.
I can see there is a documentation for Android SDK (Kotlin), IOS and NextJS. But I cannot see any SDK for MAUI.

Thank you

**Comment by nabilat** [comment]
Hi, we do not have a .net SDK for now, and it is not on our immediate roadmap either, though we will prioritize this for a release by next year. We are planning to support WebView in our Web-SDK by September, so you should be able to use it in a .net app if this works.
