### ISSUE TITLE
RPi4 (ARM64) support for the azure-ai-vision Python library? 

### ISSUE THREAD

**Issue by bbence84** [Azure-Samples/azure-ai-vision-sdk#30]
Title says it all. :) 
Will it be supported soon?

Thanks!

**Comment by bbence84** [comment]
Thanks, that's good news, that it's on the roadmap! :) I am currently using DietPi, but I can switch to Raspbian.

**Comment by dargilco** [comment]
Thank you, we have an internal work item to track ARM64 work for Linux. I will close this issue for now.
