### ISSUE TITLE
azure-ai-vision not a supported wheel on Raspbian Bullseye (Debian 11)

### ISSUE THREAD

**Issue by Packratt** [Azure-Samples/azure-ai-vision-sdk#34]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>On a system running Raspbian Bullseye (Raspberry Pi 3 or 4) with the latest version of python and pip after an apt-get update and upgrade:
1. type "python -m pip azure-ai-vision" in the console

### Any log messages given by the failure
>ERROR: azure_ai_vision-0.11.1b1-py3-none-manylinux1_x86_64.whl is not a supported wheel on this platform."

### Expected/desired behavior
>A successful install of the Azure AI Vision SDK.

### OS and Version?
> Raspbian Bullseye (Debian 11) Linux

### Versions
>Python version 3.9.2
pip version 23.1.2

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by dargilco** [comment]
Thank you @Packratt for opening this issue! As you noticed we do not yet support ARM platforms, but it is on our short roadmap and we have an internal work item for it. Is your device ARM32 or ARM64?

**Comment by Packratt** [comment]
I'm using ARM64 in small robotics and IOT devices.

**Comment by dargilco** [comment]
Thanks @Packratt!
