### ISSUE TITLE
When is the Typescript/JS SDK coming out?

### ISSUE THREAD

**Issue by awcchungster** [Azure-Samples/azure-ai-vision-sdk#55]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

When is the Typescript/JS SDK coming out?

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by dargilco** [comment]
Hi @awcchungster, we will likely have a TS/JS SDK in January.  Please implement your own JS/TS code to call the REST API directly for now.
