### ISSUE TITLE
Unable to install Azure AI Vision on MacOS 13.2 and Python 3.11

### ISSUE THREAD

**Issue by pkrefta** [Azure-Samples/azure-ai-vision-sdk#61]
Hi,

I don't know if this correct project or not for this kind of issue. Please redirect me if necessary 😃 

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: 
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
```
~
❯ sw_vers
ProductName:		macOS
ProductVersion:		13.2
BuildVersion:		22D49

~
❯ python --version
Python 3.11.1

~
❯ pip --version
pip 23.3.1 from /Users/username/.pyenv/versions/3.11.1/lib/python3.11/site-packages/pip (python 3.11)

~
❯ pip install azure-ai-vision
ERROR: Could not find a version that satisfies the requirement azure-ai-vision (from versions: none)
ERROR: No matching distribution found for azure-ai-vision
```

### Any log messages given by the failure
```
ERROR: Could not find a version that satisfies the requirement azure-ai-vision (from versions: none)
ERROR: No matching distribution found for azure-ai-vision
```

### Expected/desired behavior
> Azure AI Vision SDK should be installable 😃 

### OS and Version?
> Mac OS 13.2

### Versions
> As listed above

Thank you.

**Comment by dargilco** [comment]
@pkrefta the SDK is not yet supported on MacOS.  Please write code to call the REST APIs directly.
