### ISSUE TITLE
ImageAnalysisErrorReason.CONNECTION_FAILURE, Error code: 3 on Linux Machines

### ISSUE THREAD

**Issue by MaurusGubser** [Azure-Samples/azure-ai-vision-sdk#64]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

When using the azure-ai-vision package to connect to a vision resource, the connection to the resource fails. However, running the same Python script on a windows machine works.
Moreover, when using the REST API directly, the connection can be established. I am aware of the tickets https://github.com/Azure-Samples/azure-ai-vision-sdk/issues/40 and https://github.com/Azure-Samples/azure-ai-vision-sdk/issues/43. Also, the steps described in https://github.com/Azure-Samples/azure-ai-vision-sdk/blob/main/docs/ubuntu2204-notes.md were performed and solved the issues *until today* (2023-12-05).

### Minimal steps to reproduce
Run the `quickstart.py` example from: https://learn.microsoft.com/en-us/azure/ai-services/computer-vision/quickstarts-sdk/image-analysis-client-library-40?tabs=visual-studio%2Clinux&pivots=programming-language-python#tabpanel_1_linux

### Any log messages given by the failure
```
 Analysis failed.
   Error reason: ImageAnalysisErrorReason.CONNECTION_FAILURE
   Error code: 3
   Error message: Failed with error: HTTPAPI_OPEN_REQUEST_FAILED [0x3 | 2550]
POST https://ocr-gasmeter.cognitiveservices.azure.com/computervision/imageanalysis:analyze?api-version=2023-02-01-preview&features=caption%2Cread&gender-neutral-caption=true&language=en
```

### Expected/desired behavior
Some JSON containing the extracted information, something like:

`{"captionResult":{"text":"a man pointing at a screen","confidence":0.7767596244812012},"readResult":{"stringIndexType":"TextElements","content":"9:35 AM\nE Conference room 154584354\n#: 555-173-4547\nTown Hall\n9:00 AM - 10:00 AM\nAaron Buaion\nDaily SCRUM\n10:00 AM 11:00 AM\nChurlette de Crum\nQuarterly NI Hands\n11.00 AM-12:00 PM\nBebek Shaman\nWeekly stand up\n12:00 PM-1:00 PM\nDelle Marckre\nProduct review","pages":...}`

### OS and Version?
Failure on:
Ubuntu 22.04.3 LTS on Intel® Core™ i7-10510U CPU @ 1.80GHz × 8
Debian 11 on Intel® Core™ i7-10510U CPU @ 1.80GHz × 8

Success on:
Windows 10

### Versions
Tested with the following versions:
 azure-ai-vision 0.15.1b1
 azure-ai-vision 0.13.0b1
Python 3.10.12

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by MaurusGubser** [comment]
@dargilco Yes of course. Here's the log file:
[vision-sdk-log.txt](https://github.com/Azure-Samples/azure-ai-vision-sdk/files/13577451/vision-sdk-log.txt)

**Comment by MaurusGubser** [comment]
Sorry, maybe it is unclear, what I did. In short, when I follow your suggestion and unset `SSL_CERT_DIR` and `export OPENSSLDIR=/usr/lib/ssl`, the script fails with the same error. Three remarks:

1. `SSL_CERT_DIR` is set based on the document https://github.com/Azure-Samples/azure-ai-vision-sdk/blob/main/docs/ubuntu2204-notes.md There, it is suggested to set

```bash
$export SSL_CERT_DIR=/etc/ssl/certs
```

2. I don't understand the OPENSSLDIR variable: is this just a normal environment variable? Because when I check with

```bash
$printenv | grep SSL
OPENSSLDIR=/usr/lib/ssl
```

However, when I check
```bash
$ openssl version -d
OPENSSLDIR: "/usr/local/ssl"
```

3. I tried to solve the problem by setting a symbolic link from `/usr/local/ssl/certs` (which is empty) to `/usr/lib/ssl/certs` (where the prm files are). But still, the execution of the script fails.

I'm a bit lost :)

**Comment by dargilco** [comment]
@MaurusGubser the next version of the SDK (due out in January or early February) will be based on a new networking library that should handle your issues better. For you I suggest using Python script to call the REST API directly instead of using the SDK, and parse the resulting JSON response. You can adapt the example code below. Let me know if that worked for you.

```python
def azure_image_desc(image_url):
    import requests

    url = f"{azure_endpoint}/computervision/imageanalysis:analyze?api-version=2023-10-01&features=caption"

    headers = {
        "Ocp-Apim-Subscription-Key": azure_subscription_key,
        "Content-Type": "application/json"
    }

    data = {
        "url": image_url
    }

    response = requests.post(url, headers=headers, json=data)

    if response.status_code == 200:
        data = response.json()
        return data['captionResult']['text']
    else:
        return response.text
````

**Comment by MaurusGubser** [comment]
@dargilco Ok, thank you. Yes, the solution via REST-API works for me. I'm looking forward to the new version of the library.
