### ISSUE TITLE
c# UWP sample, VisionSource.FromFile method not working 

### ISSUE THREAD

**Issue by htwashere** [Azure-Samples/azure-ai-vision-sdk#68]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Run the UWP program (C#). Choose "Click to Select Image File" Button. Provide the location of a JPG file. Click Analyze. 

### Any log messages given by the failure
Error azac_err_failed_to_open_input_file_for_reading will be thrown. I have tried placing the JPG file in various locations, including the path of where the project solution is, it still fails

### Expected/desired behavior
>It should analyze the image the same way as the URL (VisionSource.FromUrl) method

### OS and Version?
> Windows 11

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by dargilco** [comment]
These are two locations where the UWP app has read access:

string path1 = Windows.ApplicationModel.Package.Current.InstalledLocation.Path;

This will be in the installed AppData folder (for example, for username "user-name" and app ID a467bb24-409a-b446-1075-338be52026c2_ay9t6efm8v3xw, this will be: `C:\Users\user-name\AppData\Local\Packages\a467bb24-409a-b446-1075-338be52026c2_ay9t6efm8v3xw\LocalState`)

Or
string path1 = ApplicationData.Current.LocalFolder.Path;
// For example, if you compiled the sample code in your azure-ai-vision-sdk GitHub repo clone, this will be the folder (for Debug build):  `\samples\csharp\image-analysis\uwp\bin\x64\Debug\AppX`

**Comment by htwashere** [comment]
Thank you, it worked per your explanation!
