### ISSUE TITLE
Liveness check - low level documentation and implementation

### ISSUE THREAD

**Issue by komicek** [Azure-Samples/azure-ai-vision-sdk#70]
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

We would like to implement the liveness check into our multiplatform application which is written using C++ code that runs on Android, iOS and WebAssembly inside browser.

Is there some lower level documentation or implementation for the liveness?

We assume the Kotlin and Swift implementation just calls some native libraries and performs REST requests which we could re-implement in C++ if needed.

Could we get access to this lower level implementation or their documentation?

**Comment by dipidoo** [comment]
Hi, apologies for the delayed reply. We currently have no plan to support direct usage of the lower level implementation. Please use Android and iOS libraries SDK for now. If you would like to use JavaScript, our JS SDK is in private preview and you can reach out to vision-sdk@microsoft.com for details on how to onboard for access.
