### ISSUE TITLE
unable to install on macos

### ISSUE THREAD

**Issue by yb-sid** [Azure-Samples/azure-ai-vision-sdk#72]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>pip install azure-ai-vision does not work on macos.
### Any log messages given by the failure
>ERROR: Could not find a version that satisfies the requirement azure-ai-vision (from versions: none)
ERROR: No matching distribution found for azure-ai-vision

### Expected/desired behavior
> pip install azure-ai-vision should be installed as dependency on macos.

### OS and Version?
> macOS (Sonoma 14.2.1)

### Versions
>  None

### Mention any other details that might be useful
I wanted to try out the sdk for MS Odyssey but unfortunately unable to work on exercises. The lab provided on VM has bad performance.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by dargilco** [comment]
@yb-sid are you trying to use Image Analysis or Face APIs?

**Comment by yb-sid** [comment]
Image Analysis

**Comment by dargilco** [comment]
@yb-sid we have just released a new version of the Image Analysis SDK, which is more aligned with other Microsoft Azure SDKs. The package name also changed. Please see https://learn.microsoft.com/azure/ai-services/computer-vision/sdk/install-sdk?tabs=dotnetcli%2Cterminal%2Cwindows%2Cubuntu%2Cmaven&pivots=programming-language-python .

**Comment by yb-sid** [comment]
got it , thanks for the prompt response @dargilco
