### ISSUE TITLE
GET_FACE_ARTIFACTS_ACCESS missing info on setting the right subscription

### ISSUE THREAD

**Issue by aclottan** [Azure-Samples/azure-ai-vision-sdk#74]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

in the
GET_FACE_ARTIFACTS_ACCESS.md  file,
you have the steps how to create/get the token.

it's not clear - 
1. that you MUST generate the token, using a POST and only then use the GET if you want to query for it
2. the code to generate the token are missing a MAJOR step - you must specify the right subscription !

for example

$subscriptionId = '{subscriptionid}'
$bearerToken = $(az account get-access-token --subscription $subscriptionId -o tsv).split()[0]
Invoke-WebRequest -Uri "https://face-sdk-gating-helper.azurewebsites.net/sdk/subscriptions/$subscriptionId/tokens?id=0" -Method GET -Headers @{"Authorization"="Bearer $bearerToken"}

if you dont specify it, and you have multiple subscriptions in your account, and the approved subscription isnt the default one , then you get a 500 response, that tells you nothing about the problem.

the same for the POST request

**Comment by BondarenkoInfobric** [comment]
I have the same problem but settings subscription doesn't help in my case. In all cases I get 500 (POST or GET).

The resource is configured properly (I can use Face API Rest API) plus I have Cognitive Services Contributor role.

**Comment by aclottan** [comment]
> I have the same problem but settings subscription doesn't help in my case. In all cases I get 500 (POST or GET).
> 
> The resource is configured properly (I can use Face API Rest API) plus I have Cognitive Services Contributor role.

maybe your subscription wasn't approved yet for this api.

**Comment by dipidoo** [comment]
Hi, apologies for the delayed reply. We have improved [GET_FACE_ARTIFACTS_ACCESS.md](https://github.com/Azure-Samples/azure-ai-vision-sdk/blob/9f2cb739f19b5b46d8f71724f060682892942b1f/GET_FACE_ARTIFACTS_ACCESS.md). Thank you for your suggestions.
