### ISSUE TITLE
Samples using old SDK version and don't reflect current docs SDKs

### ISSUE THREAD

**Issue by ivorb** [Azure-Samples/azure-ai-vision-sdk#76]
### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Install new SDK (1.0.0b1) for python and try to run these samples

### Any log messages given by the failure
> Visual features enum, result object etc have all changed

### Expected/desired behavior
> samples demonstrate current SDK version

### OS and Version?
> Win11

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by dargilco** [comment]
@ivorb please see https://learn.microsoft.com/azure/ai-services/computer-vision/sdk/overview-sdk for location of new samples. Image Analysis content in this GitHub repo will be deleted soon.

**Comment by ivorb** [comment]
Got it, thanks @dargilco. I got here from a link on the docs pages, I'll report an issue on that page

**Comment by ivorb** [comment]
@dargilco looks like I was mistaken, the link that got me here wasn't the docs but instead from Vision Studio. The top bar in one of the "try it out" pages links to the samples on github, as well as the bottom "Try out the SDK" - both land in this repo. I specifically found it today on the object detection page

**Comment by dargilco** [comment]
Thank you very much @ivorb, I see the out-of-date links in Vision Studio. I will make sure this will be fixes right away.
