### ISSUE TITLE
FaceRecoEngineAdapter - MapHResults.h:17 - EXC_BAD_ACCESS - iOS

### ISSUE THREAD

**Issue by rezamagnet** [Azure-Samples/azure-ai-vision-sdk#80]
> Please provide us with the following information:
> ---------------------------------------------------------------

### Minimal steps to reproduce
> I'm adding SPM to my UIKit project and adding LivenessActor.swift file from sample to my project, when I call start(usingSource: visionSource, sessionAuthorizationToken: token)  function most of the time I'm facing the issue in image below:

![Azure issue](https://github.com/Azure-Samples/azure-ai-vision-sdk/assets/10927483/b74690b0-1012-485d-a5e0-06a8d5588079)

### Any log messages given by the failure
>#5 Microsoft::CognitiveServices::Speech::Impl::FaceRecoEngineAdapter::CSpxFaceRecoEngineAdapter::GentlemenStartYourFaceEngines(Microsoft::CognitiveServices::Speech::Impl::RecoEngineAdapterMode, Microsoft::CognitiveServices::Speech::Impl::Either<Microsoft::CognitiveServices::Speech::Impl::Media::MediaOffset, Microsoft::CognitiveServices::Speech::Impl::Media::LiveMediaPosition>, std::__1::shared_ptr<Microsoft::CognitiveServices::Speech::Impl::ISpxNamedProperties> const&) at /Users/runner/work/1/s/source/core/vision_recognizers/face_reco_engine_adapter/source/face_reco_engine_adapter.cpp:1012

>#4	0x00000001037b5650 in FaceEngine_CreateImageFromBuffer ()

this is my last stack thread issue.

### Expected/desired behavior
> It's crashed on this state

### OS and Version?
> iOS 16.7.5

### Mention any other details that might be useful
I want to know what would be happens this crash occurred that I can fix that if I'm doing wrong

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by dipidoo** [comment]
Thank you for your report. Could you please detail a few more things:
- Which version of the SDK are you using?
- Since the code is EXC_BAD_ACCESS, which device were you using to test, or how much memory does it have?

**Comment by rezamagnet** [comment]
Thanks @dipidoo Sure,

Until now i'm investigating the issue, I found when I add a reference image to LivenessActor this issue occurs, I'll send you briefly of my code:

![Screenshot 2024-04-08 at 9 37 17 AM](https://github.com/Azure-Samples/azure-ai-vision-sdk/assets/10927483/962cfc43-19c9-4bc2-9ace-1e17d1df55ec)
as you can see when I add a reference image here, my crash occured.

for your answer I'm just reading from main branch with commit bf640ff for vision face framework, of course be appreciate if you could give me a link to find latest versions of the frameworks.
my testing phone is iPhone X, memory is 187 MB

**Comment by dipidoo** [comment]
Hi,

As best practice, the VerifyImage should be set during token creation. Please refer to the [API Documentation](https://westus.dev.cognitive.microsoft.com/docs/services/609a5e53f0971cb3/operations/session-create-detectlivenesswithverify-singlemodal) and [this section](https://github.com/Azure-Samples/azure-ai-vision-sdk/blob/f777ad09448442e13cf4ac1b6c8eb2017a81d7a5/samples/kotlin/face/FaceAnalyzerSample/app/src/main/java/com/example/FaceAnalyzerSample/Utils.kt#L54) of the code on how to set it.

**Comment by rezamagnet** [comment]
Hi, we followed as you told me about best practices and the problem goes. so I close this issue. Thanks
