### ISSUE TITLE
non-responsive end point detectLivenessWithVerify/singleModal/sessions in Sample App

### ISSUE THREAD

**Issue by LeilaYaghoobi70** [Azure-Samples/azure-ai-vision-sdk#86]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
When performing the network call in Postman everything just works fine but within the app after performing the api call, I won't get any response

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Android Version

### Versions
>
 faceanalyzer:0.16.2-beta.2
vision-common:0.16.2-beta.2

### Mention any other details that might be useful
After tracing I can firmly say that it can execute every commands until the line 
Pair(BufferedReader(InputStreamReader(urlConnection.inputStream)), null)
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by nabilat** [comment]
Hi @LeilaYaghoobi70 , thank you for your question. We are working on improving our documentation.

You can alter this behavior by specifying the "sendResultsToClient" flag when creating the session-authorization-token. Here's the service [documentation](https://learn.microsoft.com/en-us/rest/api/face/liveness-session-operations/create-liveness-session?view=rest-face-v1.1-preview.1&tabs=HTTP).

![image](https://github.com/Azure-Samples/azure-ai-vision-sdk/assets/15527981/ada5b378-0bc6-4b48-a761-340cfa9b058e)
