### ISSUE TITLE
Encountering Errors in Liveness Verification With Verify: Request for Error List and Explanations

### ISSUE THREAD

**Issue by LeilaYaghoobi70** [Azure-Samples/azure-ai-vision-sdk#87]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
I encounter errors when trying to check liveness with verification, and I receive various error messages such as 'action not performed' and 'environment not supported.' Is it possible for you to provide a list of errors along with explanations?

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
Android Version

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ymebrugts** [comment]
I also got these errors but I couldn't find a clear definition for any of them. 

Here is everything I found on ENVIRONMENT_NOT_SUPPORTED and COMPLETED_RESULT_QUERYABLE_FROM_SERVICE:
https://azure.github.io/azure-sdk-for-android/azure-ai-vision-faceanalyzer/com/azure/android/ai/vision/faceanalyzer/LivenessFailureReason.html#ENVIRONMENT_NOT_SUPPORTED

https://azure.github.io/azure-sdk-for-android/azure-ai-vision-faceanalyzer/com/azure/android/ai/vision/faceanalyzer/LivenessStatus.html#COMPLETED_RESULT_QUERYABLE_FROM_SERVICE

**Comment by nabilat** [comment]
Hi @LeilaYaghoobi70 , thank you for your question. We are working on improving our documentation.

The full-list of errors are listed here: [errors](https://azure.github.io/azure-sdk-for-android/azure-ai-vision-faceanalyzer/com/azure/android/ai/vision/faceanalyzer/LivenessFailureReason.html#ACTION_NOT_PERFORMED) as @ymebrugts mentioned. These errors are terminal, and the liveness session will end after these errors are surfaced.

1. ACTION_NOT_PERFORMED - This will be triggered if the application does not handle the ActionRequiredFromApplication event which should proceeded by calling setAsCompleted(). For example, the application will need to set the background color to 'black' when ActionRequiredFromApplication.DARKEN_DISPLAY even is triggered. Please check line 179 in the [sample](https://github.com/Azure-Samples/azure-ai-vision-sdk/blob/main/samples/kotlin/face/FaceAnalyzerSample/app/src/main/java/com/example/FaceAnalyzerSample/AnalyzeActivity.kt) to see how this is handled.
2. ENVIRONMENT_NOT_SUPPORTED - The "Passive" liveness technique relies on the screen providing sufficient illumination across the end-user's face to succeed. So naturally if the user is in a really bright environment, the illumination will not be sufficient to perform the liveness classification accurately, and thus this error will be triggered. The end-user should be recommended to move to a darker environment in case they would want to retry.
3. The remaining errors should be self-explanatory, please let us know if you need more clarifications.

Additionally, if face verification is enabled, then the following [verification-errors](https://azure.github.io/azure-sdk-for-android/azure-ai-vision-faceanalyzer/com/azure/android/ai/vision/faceanalyzer/RecognitionFailureReason.html) will be triggered.
