### ISSUE TITLE
Issue with Liveness Verification Output: Discrepancy with Expected Results In Sample App

### ISSUE THREAD

**Issue by LeilaYaghoobi70** [Azure-Samples/azure-ai-vision-sdk#88]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
When using Liveness with Verify Image, the output is 'COMPLETED_RESULT_QUERYABLE_FROM_SERVICE,' whereas when I use Postman, I receive the real_face result

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> 
Android Version

### Versions
>
faceanalyzer:0.16.2-beta.2
vision-common:0.16.2-beta.2

### Mention any other details that might be useful
 SDK result
AnalyzedResult(livenessStatus=COMPLETED_RESULT_QUERYABLE_FROM_SERVICE, failureReason=NONE, verificationStatus=COMPLETED_RESULT_QUERYABLE_FROM_SERVICE, confidence=0.0) 
Response
<img width="580" alt="Screenshot 1403-01-27 at 16 29 58" src="https://github.com/Azure-Samples/azure-ai-vision-sdk/assets/54942539/cad994d4-2bbc-4f16-9aa6-faffc688b962">

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ymebrugts** [comment]
I have the same issue. Did you find a solution?

**Comment by LeilaYaghoobi70** [comment]
not yet

**Comment by nabilat** [comment]
Hi @LeilaYaghoobi70 , thank you for your question. We are working on improving our documentation.

You can alter this behavior by specifying the "sendResultsToClient" flag when creating the session-authorization-token. Here's the service [documentation](https://learn.microsoft.com/en-us/rest/api/face/liveness-session-operations/create-liveness-session?view=rest-face-v1.1-preview.1&tabs=HTTP).

![image](https://github.com/Azure-Samples/azure-ai-vision-sdk/assets/15527981/5ad00089-f5c5-4b0a-a1b2-216fe3efd461)
