### ISSUE TITLE
Problems to build swift sample

### ISSUE THREAD

**Issue by jcorteztudio** [Azure-Samples/azure-ai-vision-sdk#95]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> * Open project
>* Clean Build Folder
>* Build

### Any log messages given by the failure
>  `
Showing Recent Messages
Multiple errors: unknown file type in '/Users/myuser/Library/Developer/Xcode/DerivedData/FaceAnalyzerSample-gkzsiytdsyaiqlevmpstdyuhrhye/Build/Products/Debug-iphoneos/AzureAIVisionFace.framework/AzureAIVisionFace'; unknown file type in '/Users/myuser/Library/Developer/Xcode/DerivedData/FaceAnalyzerSample-gkzsiytdsyaiqlevmpstdyuhrhye/Build/Products/Debug-iphoneos/AzureAIVisionCore.framework/AzureAIVisionCore'
`

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
macOS Sonoma 14.5
Xcode 15.4
iPhone SE, iOS 17.5.1

### Versions
> https://github.com/Azure-Samples/azure-ai-vision-sdk/tree/main/samples/swift/face/FaceAnalyzerSample
> AzureAIVisionCore: last version cocoapods and SPM
> AzureAIVisionFace: last version cocoapods and SPM

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by cheymonty** [comment]
I am also able to reproduce this issue

**Comment by dipidoo** [comment]
Hi @jcorteztudio @cheymonty thank you for reporting this issue. Could you please also share whether you have Git LFS installed and if your SPM is actively using the Git LFS during the package retrieval? Additionally, [this section of our README](https://github.com/Azure-Samples/azure-ai-vision-sdk/tree/a96d1c6c34f8991816fcfd627788adeda3c6684d/samples/swift/face/FaceAnalyzerSample#:~:text=You%20may%20encounter%20error%20if%20your%20Xcode%20has%20never%20been%20configured%20to%20use%20Git%20LFS.) contains some information about Git LFS that you might want to ensure, based on the macOS and Xcode version in the issue report.

**Comment by cheymonty** [comment]
Step 3 lets you choose between Cocoapods and Swift Package Manager. I am using Cocoapods and am using Git credential manager and get the username & password popup. Git LFS is under Swift Package Manager, do I need it still?

**Comment by jcorteztudio** [comment]
@dipidoo i follow the steps to add GIT LFS using SPM, but when compiling the project the same error still appears

**Comment by jcortezstudio** [comment]
solved, using the new documentation.
