### ISSUE TITLE
 Issue detecting face during liveness verification

### ISSUE THREAD

**Issue by LeilaYaghoobi70** [Azure-Samples/azure-ai-vision-sdk#99]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

When using Liveness,  the number of verifications received during the day is very low, while on iOS devices, a higher number of verifications is received. Considering that Liveness checks for live status by turning the screen on and off, the number of verifications significantly decreases in bright light on Android phones.

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>
faceanalyzer:0.16.2-beta.2
vision-common:0.16.2-beta.2

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by diljale** [comment]
Hello, 
Yes, we are actively developing new algorithms to ensure our solution work in all lightning conditions. You can try our Web SDK which already provides these new features https://github.com/Azure-Samples/azure-ai-vision-sdk/tree/main/samples/nextjs

These will be coming to native Android SDK soon. Your feedback will be appreciated.
